# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:

jobs:
 
  build:
    
    runs-on: ubuntu-latest    
    steps:
     
      - uses: actions/checkout@v3     
      - name: Run a one-line script
        run: echo Hello, world!


  deploy-dev:
    
    runs-on: ubuntu-latest 
    environment:
      name: DEV
      url: 'blunatrostdorf.com'
    needs: build
    steps:  
          
      - name: Run a one-line script
        run: echo deploy dev
        
  deploy-homol:
    
    runs-on: ubuntu-latest 
    environment:
      name: homol
      url: 'blunatrostdorf.com'
    needs: deploy-dev
    steps:  
          
      - name: Run a one-line script
        run: echo deploy homol


